name: clone workflow
on:
  workflow_dispatch:
jobs:
  job_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              git clone git@github.com:wyscott123/cmsc389T-P5-web-template.git